"""Utility functions and constants."""
from .constants import (
    CATEGORY_TAXONOMY,
    FORMALITY_LEVELS,
    AESTHETIC_TAGS,
    NEUTRAL_COLORS,
    SHOE_BOTTOM_PAIRINGS,
    REQUIRED_CATEGORIES_STANDARD,
    REQUIRED_CATEGORIES_FULLBODY,
    MAX_OUTFIT_ITEMS,
    MAX_ACCESSORIES,
    MAX_OUTERWEAR,
)